# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkedupload',
            name='user',
        ),
    ]
